### ISSUE TITLE
Inconsistent Alignment in Log Entries

### ISSUE THREAD

**Issue by andylizf** [panjd123/RUC-CourseSelectionTool#1]
### Description
There is an issue with inconsistent alignment in the log entries, particularly when comparing numerical values of different lengths. This misalignment affects the readability and clarity of the logs.

### Example of Issue
- Misaligned log entry:
  `2023-12-20 18:28:11,250 - INFO - req/s: 8.9     tru_reqs/s: 8.9 total: 7982`

- Correctly aligned log entry for reference:
  `2023-12-20 18:28:10,238 - INFO - req/s: 9.361   tru_reqs/s: 9.295       total: 7973`

### Suggested Fix
Replace the tab characters in the log formatting string with fixed-width spacing to ensure consistent alignment. Here is the proposed change in the code:

Original Code:
```python
f"req/s: {round(reqs, 3)}\ttru_reqs/s: {round(tru_reqs,3)}\ttotal: {log_infos.total_requests}"
```

Fixed Code:
```python
f"req/s: {round(reqs, 3):<10}tru_reqs/s: {round(tru_reqs, 3):<10}total: {log_infos.total_requests}"
```

In this modification, formatted strings with specified width are used for `req/s` and `tru_reqs/s` to maintain consistent alignment.

**Comment by panjd123** [comment]
改了
