### ISSUE TITLE
逃

### ISSUE THREAD

**Issue by DuanYi516** [panjd123/RUC-CourseSelectionTool#10]
“各位同学好，收到教务处提醒：请大家不要使用抢课软件或程序参与课程选择，使用时会影响选课系统的正常运行，目前已经从后台发现了部分同学在使用，如果再发现有账号使用，教务处将封禁相关帐号和选课权限，请大家自己登陆选择啦～谢谢！”
😭😭😭

**Comment by JasonHuang0812** [comment]
是的hhh，已经阵亡了

**Comment by Borel-Peng** [comment]
教务处记了一批名单准备上报了 部分同学被封禁进不去本科一体化
